/**
 * The Forge transformer: emits a complete, runnable MCP server project for
 * the resolved spec. Kept dependency-light so it can be upstreamed into
 * cloudflare/forge later - it only needs a Forge instance plus the manifest
 * inputs our CLI already holds.
 */
import type { OpenAPIV3 } from 'openapi-types';
import type { TransformerFn } from '../vendor/forge/index.js';
import { buildManifest, type Manifest, type ManifestOptions } from './manifest.js';
import { toKebab } from './naming.js';
import { CONFIG_FILE, type ProjectConfig } from './config.js';

export type McpTransformerOptions = ManifestOptions & {
  /** Verbatim contents of runtime/server.mjs, supplied by the CLI. */
  runtimeSource: string;
  projectConfig?: ProjectConfig;
};

function generatedPackageJson(manifest: Manifest): string {
  return (
    JSON.stringify(
      {
        name: `${toKebab(manifest.serverName)}-mcp`,
        version: '0.1.0',
        private: true,
        description: `MCP server for ${manifest.apiTitle} - generated by spec2mcp`,
        type: 'module',
        scripts: { start: 'node server.mjs', 'start:http': 'node server.mjs --transport http' },
        dependencies: { '@modelcontextprotocol/sdk': '^1.31.0' },
        engines: { node: '>=22' },
      },
      null,
      2,
    ) + '\n'
  );
}

function generatedEnvExample(manifest: Manifest): string {
  const lines: string[] = [`# Environment for the ${manifest.apiTitle} MCP server`];
  lines.push(`# Override the API base URL (default: ${manifest.baseUrl || 'none - set one here'})`);
  lines.push(`${manifest.auth.baseUrlEnvVar}=${manifest.baseUrl}`);
  for (const scheme of manifest.auth.schemes) {
    const hint =
      scheme.kind === 'basic' ? 'user:password' : scheme.kind === 'bearer' ? 'your token' : 'your API key';
    lines.push(`# Auth scheme "${scheme.schemeName}" (${scheme.kind})`);
    lines.push(`${scheme.envVar}=${hint}`);
  }
  return lines.join('\n') + '\n';
}

function generatedReadme(manifest: Manifest): string {
  const lines: string[] = [];
  lines.push(`# ${manifest.serverName} - MCP server for ${manifest.apiTitle}`);
  lines.push('');
  lines.push(`Generated by [spec2mcp](https://github.com/rowkavdev/spec2mcp) from the ${manifest.apiTitle} OpenAPI spec (API version ${manifest.apiVersion}). Exposes ${manifest.tools.length} tools over stdio or Streamable HTTP.`);
  lines.push('');
  lines.push('## Run');
  lines.push('');
  lines.push('```bash');
  lines.push('npm install');
  if (manifest.auth.schemes.length > 0) {
    lines.push(`cp .env.example .env  # fill in your credentials, then export or source it`);
  }
  lines.push('npm start  # stdio (default)');
  lines.push('PORT=3000 npm run start:http  # Streamable HTTP at http://127.0.0.1:3000/mcp');
  lines.push('```');
  lines.push('The HTTP endpoint listens on localhost only. Keep it private; it has no client authentication.');
  lines.push('');
  lines.push('## Claude Desktop');
  lines.push('');
  lines.push('```json');
  lines.push('{');
  lines.push('  "mcpServers": {');
  lines.push(`    "${manifest.serverName}": {`);
  lines.push('      "command": "node",');
  lines.push(`      "args": ["/absolute/path/to/server.mjs"]${manifest.auth.schemes.length > 0 ? ',' : ''}`);
  if (manifest.auth.schemes.length > 0) {
    lines.push('      "env": {');
    manifest.auth.schemes.forEach((s, i) => {
      lines.push(`        "${s.envVar}": "..."${i < manifest.auth.schemes.length - 1 ? ',' : ''}`);
    });
    lines.push('      }');
  }
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  lines.push('```');
  lines.push('');
  lines.push('Settings are saved in `spec2mcp.config.json`. The server reads the name, base URL and filters at startup. To add back operations excluded at generation, regenerate the project.');
  lines.push('');
  lines.push('## Tools');
  lines.push('');
  lines.push('| Tool | HTTP | Description |');
  lines.push('| --- | --- | --- |');
  for (const t of manifest.tools) {
    lines.push(`| \`${t.name}\` | ${t.method} ${t.path} | ${t.description.replace(/\|/g, '\\|')} |`);
  }
  lines.push('');
  if (manifest.auth.schemes.length > 0) {
    lines.push('## Auth');
    lines.push('');
    for (const s of manifest.auth.schemes) {
      lines.push(`- \`${s.envVar}\` - ${s.kind} (scheme \`${s.schemeName}\`)`);
    }
    lines.push('');
  }
  if (manifest.auth.warnings.length > 0) {
    lines.push('## Security warnings');
    lines.push('');
    for (const warning of manifest.auth.warnings) lines.push(`- ${warning}`);
    lines.push('');
  }
  lines.push(`Base URL: \`${manifest.baseUrl || '(set ' + manifest.auth.baseUrlEnvVar + ')'}\` - override with \`${manifest.auth.baseUrlEnvVar}\`.`);
  lines.push('');
  return lines.join('\n');
}

/** Build a Forge TransformerFn that emits the MCP server project. */
export function createMcpTransformer(doc: OpenAPIV3.Document, opts: McpTransformerOptions): TransformerFn {
  return async (forge) => {
    const manifest = buildManifest(doc, opts);
    forge.emit('operations.json', JSON.stringify(manifest, null, 2) + '\n');
    forge.emit(CONFIG_FILE, JSON.stringify(opts.projectConfig ?? { name: manifest.serverName, baseUrl: manifest.baseUrl, include: opts.include ?? [], exclude: opts.exclude ?? [] }, null, 2) + '\n');
    forge.emit('server.mjs', opts.runtimeSource);
    forge.emit('package.json', generatedPackageJson(manifest));
    forge.emit('README.md', generatedReadme(manifest));
    forge.emit('.env.example', generatedEnvExample(manifest));
    forge.emit('.gitignore', 'node_modules/\n.env\n');
  };
}
